/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_GetPidJNI */

#ifndef _Included_com_test_GetPidJNI
#define _Included_com_test_GetPidJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_GetPidJNI
 * Method:    getpid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_test_GetPidJNI_getpid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
